// react-web/src/app/notes/components/Notes.js
import React, { Component } from 'react';

import './Notes.css';
import Note from './Note';
import AddButton from './AddButton';

class Notes extends Component {  
  componentDidMount(){
    this.props.onInit();
  }
  
  render() {
    const NoteComponents = this.props.notes.map((note) => {
      return (
        <Note 
          changeNoteText={this.props.onChangeNoteText.bind(this, note.id)} 
          changeNotePosition={this.props.onChangeNotePosition.bind(this, note.id)}
          text={note.text} 
          colour={note.colour}
          left={note.left}
          top={note.top}
          disabled={note.dirty}
          key={note.id.toString()}/>
      );
    })

    return(
      <div>
        <AddButton add={this.props.onAddNote.bind(this)} colour="yellow"/>
        <AddButton add={this.props.onAddNote.bind(this)} colour="red"/>
        <AddButton add={this.props.onAddNote.bind(this)} colour="green"/>
        <AddButton add={this.props.onAddNote.bind(this)} colour="blue"/>

        {NoteComponents}
      </div>
      );
  }
}

export default Notes;

// ng-web/src/app/notes/components/notes.component.ts
import { Component, OnInit, ChangeDetectionStrategy } from '@angular/core';
import { Observable } from 'rxjs/Observable';

import { NoteComponent } from './note.component';
import { AddButtonComponent } from './add.button.component';
import { Note } from '../notes.model';
import { NotesService } from '../services/notes.service'

@Component({
  selector: 'app-notes',
  templateUrl: 'notes.component.html',
  styleUrls: ['notes.component.css'],
  providers: [NotesService],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class NotesComponent implements OnInit {
  $notes: Observable<Note[]>
  notesService: NotesService;
  
  constructor(notesService: NotesService) {
    this.notesService = notesService;
    this.$notes = this.notesService.getNotes();
  }
  
  onAddNote(colour){
    this.notesService.addNote("", colour, 200, 100);
  }
  
  onChangeNoteText(newText: string, note: Note){
    this.notesService.changeNoteText(newText, note);
  }

  onChangeNotePosition(newPosition: any, note: Note){
    this.notesService.changeNotePosition(newPosition.left, newPosition.top, note);
  }

  ngOnInit() {
    this.notesService.initialise();
  }

}

<div>
  <add-button (add)="onAddNote($event)" colour="yellow"></add-button>
  <add-button (add)="onAddNote($event)" colour="red"></add-button>
  <add-button (add)="onAddNote($event)" colour="green"></add-button>
  <add-button (add)="onAddNote($event)" colour="blue"></add-button>
  <app-note *ngFor="let note of $notes | async" 
  [text] = "note.text"
  [colour] = "note.colour"
  [left] = note.left
  [top] = note.top
  [disabled] = note.dirty
  (changeNoteText) = "onChangeNoteText($event, note)"
  (changeNotePosition) = "onChangeNotePosition($event, note)"></app-note>
  <!--{{$notes | async | json}}-->
</div>
