// ng-web/src/app/notes/components/note.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-note',
  templateUrl: 'note.component.html',
  styleUrls: ['note.component.css']
})
export class NoteComponent {
  @Input() text: string;
  @Input() top: number;
  @Input() left: number;
  @Input() colour: string;
  @Input() disabled: boolean;
  
  @Output() changeNoteText = new EventEmitter(false);
  @Output() changeNotePosition = new EventEmitter(false);

  handleChangeNotePosition(newPosition){
    if(newPosition.left != this.left || newPosition.top != this.top){
      this.changeNotePosition.emit(newPosition)
    }
  }
  handleChangeNoteText(text){
    if(text != this.text){
      this.changeNoteText.emit(text)
    }
  }
}
<textarea #noteText 
  [style.top.px] = "top"
  [style.left.px] = "left"
  (draggable)="handleChangeNotePosition($event)"
  (blur)="handleChangeNoteText(noteText.value)" 
  [disabled] = "disabled"
  [ngClass] = "colour + '-note'"
  [defaultValue]= "text"></textarea>

// react-web/src/app/notes/Note.js
import React, { Component } from 'react';
import './Note.css';
import draggable from '../shared/draggable'

//extend the textarea with draggable behaviour by employing a Higher Order Component function (HOC) https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750
const PositionedTextArea = (props) => { return ( <textarea  {...props} />); }
let DraggableTextArea = draggable(PositionedTextArea)

class Note extends Component {
  handleChangeNoteText($event){
    this.props.changeNoteText($event.target.value);
  }

  handleChangeNotePosition($event){
    this.props.changeNotePosition($event.target.value);
  }

  render(){
    //onBlur, disabled, className and defaultValue belong to the textarea, left, top and onEndDrag will be 'consumed' by the draggable HOC
    return (
      <DraggableTextArea
        top={this.props.top}
        left={this.props.left}
        onEndDrag={this.handleChangeNotePosition.bind(this)}
        onBlur={this.handleChangeNoteText.bind(this)}
        disabled={this.props.disabled} 
        className={this.props.colour + '-note'}
        defaultValue={this.props.text}
        />
      );
  }
}

export default Note;
