// ng-web/src/app/notes/components/notes.component.ts
import { Component, OnInit, ChangeDetectionStrategy } from '@angular/core';
import { Observable } from 'rxjs/Observable';

import { NoteComponent } from './note.component';
import { AddButtonComponent } from './add.button.component';
import { Note } from '../notes.model';
import { NotesService } from '../services/notes.service'

@Component({
  selector: 'app-notes',
  templateUrl: 'notes.component.html',
  styleUrls: ['notes.component.css'],
  providers: [NotesService],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class NotesComponent implements OnInit {
  $notes: Observable<Note[]>
  notesService: NotesService;
  
  constructor(notesService: NotesService) {
    this.notesService = notesService;
    this.$notes = this.notesService.getNotes();
  }
  
  onAddNote(colour){
    this.notesService.addNote("", colour, 200, 100);
  }
  
  onChangeNoteText(newText: string, note: Note){
    this.notesService.changeNoteText(newText, note);
  }

  onChangeNotePosition(newPosition: any, note: Note){
    this.notesService.changeNotePosition(newPosition.left, newPosition.top, note);
  }

  ngOnInit() {
    this.notesService.initialise();
  }

}

<div>
  <add-button (add)="onAddNote($event)" colour="yellow"></add-button>
  <add-button (add)="onAddNote($event)" colour="red"></add-button>
  <add-button (add)="onAddNote($event)" colour="green"></add-button>
  <add-button (add)="onAddNote($event)" colour="blue"></add-button>
  <app-note *ngFor="let note of $notes | async" 
  [text] = "note.text"
  [colour] = "note.colour"
  [left] = note.left
  [top] = note.top
  [disabled] = note.dirty
  (changeNoteText) = "onChangeNoteText($event, note)"
  (changeNotePosition) = "onChangeNotePosition($event, note)"></app-note>
  <!--{{$notes | async | json}}-->
</div>

// react-web/src/app/notes/Notes.js
import React, { Component } from 'react';
import './Notes.css';
import Note from './Note';


class Notes extends Component {
  notes = [
    {
      "id": 1,
      "text": "ReactNg",
      "colour": "red",
      "left": 200,
      "top": 100
    },
    {
      "id": 2,
      "text": "Comparing React and Angular in a non trivial app.",
      "colour": "blue",
      "left": 300,
      "top": 200
    },
    {
      "id": 3,
      "text": "Companion Video available soon.",
      "colour": "yellow",
      "left": 400,
      "top": 300
    }
  ];
  
  handleOnAdd(colour){
    console.log('TODO - Dispatch a notes add action with colour ' + colour);
  }

  onChangeNoteText(newText){
    console.log('TODO - Dispatch a notes text update action with text ' + newText);
  }

  onChangeNotePosition(newPosition){
    console.log('TODO - Dispatch a notes position update action with position ' + newPosition);
  }

  render() {
    const NoteComponents = this.notes.map((note) => {
      return (
        <Note 
          changeNoteText={this.onChangeNoteText.bind(this)} 
          changeNotePosition={this.onChangeNotePosition.bind(this)}
          text={note.text} 
          colour={note.colour}
          left={note.left}
          top={note.top}
          key={note.id.toString()}/>
      );
    })

    return(
      <div>
      {/*
        <AddButton onAdd={this.handleOnAdd.bind(this)} colour="yellow"/>
        <AddButton onAdd={this.handleOnAdd.bind(this)} colour="red"/>
        <AddButton onAdd={this.handleOnAdd.bind(this)} colour="green"/>
        <AddButton onAdd={this.handleOnAdd.bind(this)} colour="blue"/>
      */}
        {NoteComponents}
      </div>
      );
  }
}

export default Notes;
